language: c

latex: true

notifications:
  webhooks: https://www.travisbuddy.com/
  on_success: never

addons:
  apt:
    packages:
      - texlive
      - qttools5-dev-tools
      - qt5-default

addons:
  homebrew:
    packages:
      - qt
    casks:
      # Don't uncomment this unless you want to spend ten extra minutes on
      # every build.
      - mactex


matrix:
  include:
    - os: linux
      dist: trusty
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode10
    - os: osx
      osx_image: xcode10.1

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew config; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew ls; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew doctor; fi
  # Don't bother brew updating; takes too long.
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - which gcc
  - gcc --version
  - which tex
  - if which tex; then ls -l $(which tex); fi
  - tex --version && true
  - which latex && true
  - if which latex; then ls -l $(which tex); fi
  - latex --version && true
  - env
  - mount
  - df -h
  - pwd
  - qhelpgenerator -qt5 -v
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then qtchooser -list-versions; fi
