language: c

latex: true

os:
  - linux
  - osx
dist: xenial

addons:
  apt:
    packages:
      - texlive
      - octave
      - qttools5-dev-tools
      - libqt5sql5-sqlite
      
addons:
  homebrew:
    casks:
      - mactex

matrix:
  include:
    - os: linux
      dist: trusty
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode10
    - os: osx
      osx_image: xcode10.1

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew config; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew ls; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew doctor; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ls -l /Applications; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then apt list --installed; fi
  - which gcc
  - gcc --version
  - which tex
  - tex --version
  - ls -l $(which tex)
  - env
  - mount
  - df -h
  - pwd
